#!/usr/bin/env bash

# setting up the terminal prompt
BOLD="\[\033[1m\]"
OFF="\[\033[m\]"
GREEN="\[\e[0;32m\]"
BLUE="\[\e[34m\]"
RED="\[\e[1;31m\]"

HOST="\h"
USER="\u"
DIR="\w"
FOLDER="\W"
NEWLINE="\n"
DATE="\d"
TIME="\t"

export PS1="${NEWLINE}${GREEN}${BOLD}${USER}@${HOST}${OFF}:${BLUE}${BOLD}${DIR}${NEWLINE}${RED}$ ${OFF}"

# creating GOPATH for GOLANG usage
export GOPATH=$HOME/wksp/golang
export PATH=$PATH:$(go env GOPATH)/bin

# groovy
export GROOVY_HOME=/usr/local/opt/groovy/libexec

# add home bin to path
export PATH="~/bin:$PATH"

# ensuring history is long and searchable
HISTSIZE=49999
HISTFILESIZE=49999

# bash completion - somethings become more useful when there is an associate bash completion script 
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# got aliases???
[ -f ~/.aliases ] && . ~/.aliases

# got secrets??? everybody's got secrets?!? 
# change of heart ... don't source unless necessary
# [ -f ~/.secrets ] && . ~/.secrets

# ensuring ls & tree show things in full fotochrome
[ -f ~/.lscolors ] && . ~/.lscolors

# aws cli scripts are located in this directory
if [ -d ~/Library/Python/3.6/bin/ ]; then
	export PATH="~/Library/Python/3.6/bin/:$PATH"
fi

# nvm stuff
export NVM_DIR="$HOME/.nvm"
NVM_SH="$NVM_DIR/nvm.sh"
NVM_BASH="$NVM_DIR/bash_completion"
[ -s "$NVM_SH" ] && . "$NVM_SH" # This loads nvm
[ -s "$NVM_BASH" ] && . "$NVM_BASH"  # This loads nvm bash_completion

if [ -d ~/android-sdk/platform-tools/ ]; then
  export PATH="$PATH:~/android-sdk/platform-tools/"
fi
