set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plugin 'tpope/vim-fugitive', {'rtp': 'vim-fugitive/plugin/'}
Plugin 'scrooloose/nerdtree'
" Plugin 'saltstack/salt-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'elzr/vim-json'
" Plugin 'aperezdc/vim-template'
Plugin 'davidhalter/jedi-vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'vim-scripts/nginx.vim'
Plugin 'vimwiki/vimwiki'
Plugin 'hashivim/vim-hashicorp-tools'
" Plugin 'Valloric/YouCompleteMe'
Plugin 'martinda/Jenkinsfile-vim-syntax'
Plugin 'fatih/vim-hclfmt'
Plugin 'b4b4r07/vim-hcl'
Plugin 'fatih/vim-go' "https://github.com/fatih/vim-go

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" :source %
" :PluginInstall
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this 

"------------------------------------------------
" Powerline setup
set laststatus=2
set term=xterm-256color
"------------------------------------------------
nmap <F5> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
"------------------------------------------------
"
" <leader> is defined as \
" Use <leader> l to toggle display of whitespace
nmap <F4> :set list!<CR>
" And set some nice chars to do it with
set listchars=tab:»\ ,eol:¬

" keymap line numbers toggle
nmap <F2> :set invnumber<CR>
nmap <F3> :set invrelativenumber<CR>

" automatically change window's cwd to file's dir
set autochdir

let g:vim_markdown_folding_disabled = 1
let g:vim_json_syntax_conceal = 0
let g:ycm_python_binary_path = 'python'

" backspace
set backspace=indent,eol,start

set tabstop=2
set shiftwidth=2
" uncomment line below to uses spaces instead of tabs
" set expandtab
set nu
" set relativenumber
syntax on

":VimwikiAll2HTML -- Convert all your wiki links to HTML
"<Leader>ww -- Open default wiki index file.
"<Leader>wt -- Open default wiki index file in a new tab.
"<Leader>ws -- Select and open wiki index file.
"<Leader>wd -- Delete wiki file you are in.
"<Leader>wr -- Rename wiki file you are in.
"<Enter> -- Follow/Create wiki link
"<Shift-Enter> -- Split and follow/create wiki link
"<Ctrl-Enter> -- Vertical split and follow/create wiki link
"<Backspace> -- Go back to parent(previous) wiki link
"<Tab> -- Find next wiki link
"<Shift-Tab> -- Find previous wiki link
